### ISSUE TITLE
asynchronization between sliding anaimation and change of active bullet of pagination

### ISSUE THREAD

**Issue by alhoseany** [nicinabox/superslides#26] opened 2012-12-09 22:30 UTC
hi, thanks for this great plugin. i only have one problem with it.
the sliding animation goes complete before the corresponding bullet in the pagination becomes active also, the 'slides.animated' event is fired very far away from the start of the sliding animation. meaning that the event is fired after the animation is done. i need it to be fired once the animation is started.

**Comment by nicinabox** [comment] 2012-12-10 16:46
That is correct. [Pagination is updated on the `slides.animated` event](https://github.com/nicinabox/superslides/blob/master/src/jquery.superslides.coffee#L286).

This event happens after animation finishes (that's why it's past tense). This is by design. There is no event for "before animate". 

Perhaps you could give a use case for "before animate"?

**Comment by alhoseany** [comment] 2012-12-10 19:33
thanks i added a new event for start animation and i add it in the line 242. the animate function now is like this:

animate = function(direction) {
    var next, position, prev,
      _this = this;
    if (animating || direction >= size || direction === this.current) {
      return;
    }
    animating = true;
    prev = this.current || direction - 1 || 0;

```
switch (direction) {
  case 'next':
    position = width * 2;
    direction = -position;
    next = this.current + 1;
    if (size === next) {
      next = 0;
    }
    break;
  case 'prev':
    position = direction = 0;
    next = this.current - 1;
    if (next === -1) {
      next = size - 1;
    }
    break;
  default:
    next = +direction;
    if (isNaN(next)) {
      console.log('isnan');
      animating = false;
      return false;
      break;
    }
    if (next > prev) {
      position = width * 2;
      direction = -position;
    } else {
      position = direction = 0;
    }
}
this.current = next;
$children.removeClass('current').eq(this.current).css({
  left: position,
  display: 'block'
});
$container.trigger('slides.animate', [_this.current, next, prev]);  //  ***added line here*** 
$control.animate({
  useTranslate3d: (is_mobile ? true : false),
  left: direction
}, $.fn.superslides.options.slide_speed, $.fn.superslides.options.slide_easing, function() {
  $control.css({
    left: -width
  });
  $children.eq(next).css({
    left: width,
    zIndex: 2
  });
  $children.eq(prev).css({
    left: width,
    display: 'none',
    zIndex: 0
  });
  $children.eq(_this.current).addClass('current');
  if (first_load) {
    $container.fadeIn('fast');
    $container.trigger('slides.initialized');
    first_load = false;
  }
  animating = false;
  return $container.trigger('slides.animated', [_this.current, next, prev]);
});
return this.current;
```

  };

i use this event to make other effects with jquery with the slider. i tried to use this event on the pagination like this:

```
    if (options.pagination) {
      $window.on("slides.initialized", function(e) {
        $(_this).append($("<nav>", {
          "class": 'slides-pagination'
        }));
        return $children.each(function(i) {
          return addPaginationItem(i);
        });
      }).on("slides.animate", function(e, current, next, prev) {    // event here
        var $pagination;
        $pagination = $(".slides-pagination");
        $(".active", $pagination).removeClass("active");
        return $("a", $pagination).eq(current).addClass("active");
      }).on("click", ".slides-pagination a", function(e) {
        var index;
        if (!options.hashchange) {
          e.preventDefault();
        }
        index = this.hash.replace(/^#/, '');
        return animate(index);
      }).on('hashchange', function(e) {
        var index;
        index = location.hash.replace(/^#/, '');
        stop();
        return animate(index);
      });
    }
    return start();
  });
}
```

  };

and it works great but the pagination is not setup on slideshow initialization. where is the part of the code that i can use to set the pagination on initialization.

thanks

**Comment by nicinabox** [comment] 2012-12-10 20:06
It's in your paste after `if (options.pagination)`. Each pagination item is added on the `slides.initialized` event.

**Comment by alhoseany** [comment] 2012-12-10 20:11
yes but the 1st item on pagination didnt assign active class on initialization.

**Comment by nicinabox** [comment] 2012-12-10 20:16
Right. Because your animate event fires before the initialization event, the pagination items haven't even been added to the page yet.

**Comment by alhoseany** [comment] 2012-12-10 20:20
ok, is there is anyway to fix this? where the slides animation starts exactly in the code?

**Comment by nicinabox** [comment] 2012-12-10 20:28
Sorry, I'm a little confused at why you need to change all the internals. The point of using an event is so that you can hook into it outside of the plugin code. 

If you remove internals that depend on events to initialize properly, you're gonna have a bad time. Why not just add the `slides.animate` event before animation occurs, then listen for that event in your application?

**Comment by alhoseany** [comment] 2012-12-10 20:36
i know. i did that and it is great. what i am looking for now is making the pagination change once the slide animation start not after it is ended. this is cant be done outside of the code itself. because it is already there.

the current situation is that the pagination changes after slide animation finished. this is not right for any slideshow. if you check any slideshow out there. nivoslider or supersized . i just want to know how to make the 1st pagination item active on initialization. that is it.

thanks. i am sorry if i am wasting your time. i love the plugin and it does exactly what i need except this part.

**Comment by nicinabox** [comment] 2012-12-10 20:41
Ah I see. You're just wanting to change the functionality so have the active state on before animate. 

Abstract the the pagination code into a method an call it from both `slides.initialized` and `slides.animate`

``` javascript
var updatePagination = function() {
  var $pagination;
  $pagination = $(".slides-pagination");
  $(".active", $pagination).removeClass("active");
  return $("a", $pagination).eq(current).addClass("active");
};
```

``` javascript
$window.on("slides.initialized", function(e) {
  $(_this).append($("<nav>", {
    "class": 'slides-pagination'
  }));
  return $children.each(function(i) {
    return addPaginationItem(i);
  });
  updatePagination();

}).on("slides.animate", function(e, current, next, prev) { 
  updatePagination()
})
```

**Comment by alhoseany** [comment] 2012-12-10 22:57
thanks, i changed this part about the 1st load and now everything works fine. here it is:

``` javascript
      if (first_load) {
        $container.fadeIn('fast');
        $container.trigger('slides.initialized');
        $(".slides-pagination a").eq(0).addClass("active");
        first_load = false;
      }
```

**Comment by nicinabox** [comment] 2012-12-10 23:02
Great! I'm going to close this then if it's resolved. Feel free to open an issue if you find problems with the production code.

**Closed as completed by nicinabox** 2012-12-10 23:02 UTC

**Comment by nicinabox** [comment] 2012-12-15 02:57
0.5.0 will have the pagination updating before animation.
