### ISSUE TITLE
Center images

### ISSUE THREAD

**Issue by Spannor** [nicinabox/superslides#13] opened 2012-10-04 15:05 UTC
Nice work!

I'm using landscape images, but when used on mobile devices such as tablets, if you change the device orientation from landscape to portrait the images are left-aligned so the important part of them are hidden. I've tried to change the css so that the images are "centered" but I've had no success. Can you tell me where I'm going wrong?

Thanks!

**Comment by nicinabox** [comment] 2012-10-05 14:04
I've noticed this bug as well. It's a little tricky to reproduce because it doesn't happen when you resize the browser--they stay centered. Only on mobile devices does it seem to occur like this and I'm not sure why.

**Comment by nicinabox** [comment] 2012-10-17 17:58
This has now been fixed in the dev branch.

**Closed as completed by nicinabox** 2012-10-17 17:58 UTC
Labels: bug
